# Generated by Django 5.1 on 2025-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes about the category', null=True),
        ),
    ]
