# Generated by Django 5.1 on 2025-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_item_created_at_alter_item_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Selling Price'),
        ),
    ]
