# Generated by Django 5.1 on 2025-03-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_item_price_item_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expiring_date',
        ),
    ]
