# Generated by Django 5.1 on 2025-03-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='product',
        ),
    ]
