# Generated by Django 5.1 on 2025-03-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_item_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manufacturing_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='store.item')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'db_table': 'batch',
                'ordering': ['-manufacturing_date'],
                'indexes': [models.Index(fields=['manufacturing_date'], name='manufacturing_date_idx'), models.Index(fields=['expiration_date'], name='expiration_date_idx'), models.Index(fields=['product', 'manufacturing_date'], name='product_manufacturing_idx')],
            },
        ),
    ]
