# Generated by Django 5.1 on 2025-03-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
    ]
