# Generated by Django 5.1 on 2025-04-06 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_store_type'),
        ('store', '0018_rawmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('packaging', 'Packaging Material'), ('other', 'Other Operational Item')], default='packaging', max_length=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendor', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Operations Inventory',
                'verbose_name_plural': 'Operations Inventories',
                'db_table': 'operations_inventory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='operations__type_cb1fe3_idx'), models.Index(fields=['vendor'], name='operations__vendor__d492c4_idx')],
            },
        ),
    ]
