# Generated by Django 5.1 on 2025-04-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0019_operationsinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock_type', models.CharField(choices=[('product', 'Product Stock'), ('raw_material', 'Raw Material Stock'), ('operations', 'Operations Stock')], default='product', max_length=13)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.batch')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['item', 'rawmaterial', 'operationsinventory']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Unified Stock',
                'verbose_name_plural': 'Unified Stock',
                'db_table': 'stock',
                'indexes': [models.Index(fields=['stock_type'], name='stock_stock_t_e88385_idx'), models.Index(fields=['content_type', 'object_id'], name='stock_content_6157dc_idx')],
            },
        ),
    ]
