# Generated by Django 5.1 on 2025-04-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0020_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('expiration', 'Expiration Alert')], default='low_stock', max_length=10)),
                ('related_item_type', models.CharField(choices=[('product', 'Product'), ('raw_material', 'Raw Material')], default='product', max_length=13)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('notice', 'Notice')], default='notice', help_text='Severity level osf the alert', max_length=8)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=8)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['item', 'rawmaterial']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Inventory Alert',
                'verbose_name_plural': 'Inventory Alerts',
                'db_table': 'alerts',
                'indexes': [models.Index(fields=['alert_type'], name='alerts_alert_t_eda531_idx'), models.Index(fields=['status'], name='alerts_status_0e4dc1_idx'), models.Index(fields=['content_type', 'object_id'], name='alerts_content_9202e2_idx')],
            },
        ),
    ]
