# Generated by Django 5.1 on 2025-04-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0022_baserecipe_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('sales_trend', 'Sales Trend'), ('top_selling', 'Top Selling'), ('vendor_performance', 'Vendor Performance'), ('other', 'Other')], default='other', max_length=20)),
                ('related_entity_id', models.PositiveIntegerField()),
                ('metric', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('calculated_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('related_entity_type', models.ForeignKey(limit_choices_to={'model__in': ['item', 'vendor']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'insights',
                'ordering': ['-calculated_date'],
            },
        ),
    ]
