# Generated by Django 5.1 on 2025-01-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('ST', 'Staff'), ('EX', 'Executive'), ('AD', 'Admin')], max_length=12, null=True, verbose_name='Role'),
        ),
    ]
