# Generated by Django 5.1 on 2025-03-29 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Raw Material Vendor', 'verbose_name_plural': 'Raw Material Vendors'},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Store Name'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='raw_material_vendor',
        ),
    ]
