# Generated by Django 5.1 on 2025-03-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_options_rename_phone_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='store_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=10),
        ),
    ]
