# Generated by Django 5.1 on 2025-03-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Source/origin of the purchase', max_length=255, verbose_name='From')),
                ('date', models.DateTimeField(verbose_name='Purchase Date')),
                ('description', models.TextField(verbose_name='Purchase Details')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal Amount')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Non-Inventory Purchase',
                'verbose_name_plural': 'Non-Inventory Purchases',
                'db_table': 'other_purchase',
                'ordering': ['-date'],
            },
        ),
    ]
