# Generated by Django 5.1 on 2025-03-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_otherpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPurchaseDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(choices=[('unit', 'Unit'), ('box', 'Box'), ('pack', 'Pack'), ('set', 'Set'), ('kg', 'Kilogram'), ('liter', 'Liter')], default='unit', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('stationary', 'Stationary'), ('sanitary', 'Sanitary'), ('furniture', 'Furniture'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('other_purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transactions.otherpurchase')),
            ],
            options={
                'verbose_name': 'Detailed Non-Inventory Purchase',
                'verbose_name_plural': 'Detailed Non-Inventory Purchases',
                'db_table': 'other_purchase_detailed',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='other_purch_type_3659dd_idx'), models.Index(fields=['unit_of_measure'], name='other_purch_unit_of_3b34f1_idx')],
            },
        ),
    ]
