# Generated by Django 5.1 on 2025-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_otherpurchasedetailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Effective Date')),
                ('valid_from', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('offer', 'Special Offer'), ('discount', 'Discount')], default='offer', max_length=8, verbose_name='Offer/Discount Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer/Discount',
                'verbose_name_plural': 'Offers & Discounts',
                'db_table': 'offer_discount',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['type'], name='offer_disco_type_84a81c_idx'), models.Index(fields=['valid_from', 'valid_till'], name='offer_disco_valid_f_16a7ea_idx')],
            },
        ),
    ]
