# Generated by Django 5.1 on 2025-04-06 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_store_type'),
        ('store', '0017_remove_item_vendor'),
        ('transactions', '0006_offerdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDiscountDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offer', 'Offer'), ('discount', 'Discount')], default='offer', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_details', to='transactions.offerdiscount')),
                ('offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_details', to='transactions.offerdiscount')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item', verbose_name='Related Product')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Related Vendor')),
            ],
            options={
                'verbose_name': 'Offer/Discount Detail',
                'verbose_name_plural': 'Offer/Discount Details',
                'db_table': 'offer_discount_detailed',
                'indexes': [models.Index(fields=['type'], name='offer_disco_type_492d45_idx'), models.Index(fields=['offer_id', 'discount_id'], name='offer_disco_offer_i_7c6b08_idx')],
            },
        ),
    ]
