# Generated by Django 5.1 on 2025-04-19 16:37

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_store_type'),
        ('transactions', '0007_offerdiscountdetailed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='total_value',
            new_name='grand_total',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the purchase was recorded'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='raw_material_vendor',
            field=models.ForeignKey(db_column='raw_material_vendor_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='raw_material_vendor', unique=True),
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
