# Generated by Django 5.1 on 2025-04-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_created_at_alter_customer_updated_at'),
        ('transactions', '0008_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='raw_material_vendor',
            field=models.ForeignKey(db_column='raw_material_vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.vendor'),
        ),
    ]
