# Generated by Django 5.1 on 2025-04-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alerts'),
        ('transactions', '0009_alter_purchase_raw_material_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consumable', 'Consumable'), ('non-consumable', 'Non‑Consumable')], max_length=15)),
                ('unit_of_measure', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, to='transactions.purchase')),
                ('raw_material', models.ForeignKey(db_column='raw_material_id', on_delete=django.db.models.deletion.CASCADE, to='store.rawmaterial')),
            ],
            options={
                'db_table': 'purchase_detailed',
                'ordering': ['-created_at'],
            },
        ),
    ]
