# Generated by Django 5.1 on 2025-04-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_purchasedetailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetailed',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
