# Generated by Django 5.1 on 2025-04-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_purchasereport_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereport',
            name='time_frame',
            field=models.CharField(choices=[('custom', 'Custom'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='custom', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='time_frame',
            field=models.CharField(choices=[('custom', 'Custom'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='custom', max_length=10),
        ),
    ]
